 project: 
  type: website
  output-dir: docs
  
  website: 
  title: "Alaina-Lawrence"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd 
    theme:
      - cosmo
      - brand
    css: styles.css